### ISSUE TITLE
使用https://github.com/natesales/q进行测试 报错

### ISSUE THREAD

**Issue by myrshfrs** [crzidea/doh#3]
同时用9.9.9.9和搭建的doh进行测试，9.9.9.9结果正确，搭建的doh报错

![屏幕截图 2024-09-16 104234](https://github.com/user-attachments/assets/f67a0781-e902-4eb7-806a-35a8eb179a94)

**Comment by crzidea** [comment]
1. workers.dev 在墙内时不能直接访问的，需要使用代理。
2. 换个自己的域名也是可以访问的，墙只是干扰了 workers.dev，不会影响自己注册的域名。
3. 每账号的 workers 有 10 万的访问量上限，尽量使用自己账号的 worker。

**Comment by crzidea** [comment]
另外尽量不要在这里暴漏自己的 IP，保护好自己[狗头]。
