### ISSUE TITLE
请问按照 README 的步骤搭建之后，还需要折腾 Github Actions 吗？

### ISSUE THREAD

**Issue by choicky** [crzidea/doh#4]
大佬的想法很有创意，多谢大佬。我已按照英文版的 [README](https://github.com/crzidea/doh)  搭建好。

我见中文介绍里面提到 `Github Actions` ，但 英文版的 [README](https://github.com/crzidea/doh) 没有提到。我还需要对 `Github Actions` 做什么设置吗？

**Comment by crzidea** [comment]
在项目设置（Github 项目 url + /settings/secrets/actions）里填好自己的 Secret 就可以了。可以在 Actions 手动触发运行一下，看看是不是能正常运行，能运行就不用管了，每周自动更新 IP 库。
